[workspace]
resolver = "2"
members = ["kuberic-page", "kuberic-rocksdb", "kuberic-rustfs"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/youyuanwu/kuberic-apps"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.8"
bytes = "1"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
fs2 = "0.4"
kuberic-runtime = { git = "https://github.com/youyuanwu/kuberic", rev = "131ccc9ddd7dbba9fb910d1000d4fbd2206c548a" }
kuberic-native-runtime = { package = "kuberic-runtime", git = "https://github.com/Joyjeet045/kuberic", rev = "690c91c330915fb0fdef2d2e6c1afaa2125862e9", default-features = false, features = ["native"] }
kuberic-controller = { git = "https://github.com/Joyjeet045/kuberic", rev = "690c91c330915fb0fdef2d2e6c1afaa2125862e9", features = ["native"] }
crc32fast = "1"
reqwest = { version = "0.12.28", default-features = false, features = ["rustls-tls"] }
rocksdb = { version = "=0.25.0", default-features = false, features = ["bindgen-runtime"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
tracing = "0.1"
tracing-subscriber = "0.3"
